version: "3"

services:
  api:
    build:
      context: ./docker/api
    container_name: ${PROJECT_NAME}-api
    volumes:
      - ./api:${API_DIRECTORY}
    networks:
      - ${PROJECT_NAME}

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      practic22:
        ipv4_address: ${FRONTEND_IPV4}

  nginx:
    build:
      context: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./api:${API_DIRECTORY}
      - ./frontend:${FRONTEND_DIRECTORY}
    depends_on:
      - api
    environment:
      FRONTEND_DIRECTORY: ${FRONTEND_DIRECTORY}
      API_DIRECTORY: ${API_DIRECTORY}
    networks:
      practic22:
        ipv4_address: ${NGINX_IPV4}

  mysql:
    image: mysql:8.0.23
    container_name: ${PROJECT_NAME}-mysql
    restart: unless-stopped
    volumes:
      - mysqls:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #login:root password:root
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    hostname: mysql.docker
    networks:
      practic22:
        ipv4_address: ${MYSQL_IPV4}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${PHPMYADMIN_ROOT_PASSWORD}
      MYSQL_USER: ${PHPMYADMIN_MYSQL_USER}
      MYSQL_PASSWORD: ${PHPMYADMIN_MYSQL_PASSWORD}
      UPLOAD_LIMIT: 20M
    networks:
      practic22:
        ipv4_address: ${PHPMYADMIN_IPV4}


volumes:
  api:
  frontend:
  nginx:
  data:
  mysqls:

networks:
  practic22:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
