version: "3"

services:

  api:
    build:
      dockerfile: Dockerfile.xlocal
    restart: unless-stopped
    volumes:
      - ./docker/api/php/config/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-xdebug.ini
      - ./docker/api/php/config/docker-opcache.ini:/usr/local/etc/php/conf.d/docker-opcache.ini
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: "client_host=172.22.0.1"
      XDEBUG_SESSION: 1
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - mysql
    networks:
      practic22:
        ipv4_address: ${API_IPV4}

  nginx:
    build:
      dockerfile: Dockerfile.local
    restart: unless-stopped
    volumes:
      - ./docker/certs/local:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    environment:
      NODE_ENV: dev
      NGINX_HOST: ${NGINX_HOST_LOCAL}
      NGINX_PORT: ${NGINX_PORT_LOCAL}
      NGINX_CERT_CRT: ${NGINX_CERT_CRT_LOCAL}
      NGINX_CERT_KEY: ${NGINX_CERT_KEY_LOCAL}

volumes:
  mysql:
