# https://github.com/lexik/LexikJWTAuthenticationBundle
lexik_jwt_authentication:
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'

  token_ttl: 3600 # token TTL in seconds
  user_identity_field: email

  token_extractors:
    cookie:
      enabled: true
      name: BEARER

  set_cookies:
    BEARER:
      lifetime: 3600
      samesite: lax
      path: /
      domain: null
      secure: false
      httpOnly: false


#    remove_token_from_body_when_cookies_used: false
